use_gpu: True
device: 10
early_stop:
  patience: 0
seed: 618
federate:
  mode: standalone
  method: Ditto
  local_update_steps: 3
  batch_or_epoch: epoch
  total_round_num: 500
  sample_client_rate: 0.1
  # unseen_clients_rate: 0.2
  client_num: 200
personalization:
  K: 5
  beta: 1.0
  local_param: []
  local_update_steps: 2
  lr: 0.1
  regular_weight: 0.1
  share_non_trainable_para: false
data:
  seed: 12345
  dataset: ['train', 'val', 'test', 'poison']
  root: data/
  type: femnist
  splits: [0.6,0.2,0.2]
  batch_size: 32
  subsample: 0.05
  num_workers: 0
  # transform: [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
  transform: [['ToTensor']]
model:
  type: convnet2
  hidden: 2048
  out_channels: 62
  # dropout: 0.5
optimizer:
  lr: 0.1
  weight_decay: 0.0
grad:
  grad_clip: -1.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  best_res_update_round_wise_key: 'test_loss'
  freq: 10
  # split: ['test']
  # metrics: ['acc', 'correct', 'poison_attack_acc']
  # split: ['test','poison']
  split: ['test','val','poison']
  metrics: ['acc', 'correct']
attack:
  setting: 'fix'
  freq: 1
  # insert_round: 300
  attack_method: 'backdoor'
  attacker_id: [1,2,3]
  label_type: 'dirty'
  trigger_type: edge
  edge_num: 400
  poison_ratio: 0.5
  target_label_ind: 1
  self_opt: False
  self_lr: 0.1
  self_epoch: 6
  scale_poisoning: False
  scale_para: 5.0
  pgd_poisoning: False
  robustness: False
  mean: [0.1307]
  std: [0.3081]
expname: bencn_ditto_edge